Models/DataModels/ClientOrder.cs
namespace coursework.Models.DataModels
{
    public class ClientOrder
    {
        public string FullName { get; set; }
        public string Specialty { get; set; }
        public DateTime OrderTime { get; set; }
    }
}

Models/DataModels/Manager.cs
namespace coursework.Models.DataModels
{
    public class Manager:User{
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
    }
}

Controllers/ManagerController.cs
using coursework.DB;
using coursework.DB.RequestRoad;
using coursework.Models.DataModels;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using coursework.Valid;
using coursework.Models.TriggerModel;

namespace coursework.Controllers {
    public class ManagerController : Controller {
        // Виконавець для доступу до бази даних
        public Performer _performer;

        // Конструктор, який приймає виконавця
        public ManagerController(DataBaseConnect db, Performer performer) {
            _performer = performer;
        }

        // Дія для відображення профілю менеджера (GET-запит)
        [HttpGet]
        [Route("ManagerController/Profile")]
        public IActionResult Profile() {
            // Отримання даних менеджера з сесії та десеріалізація їх
            var usertJson = HttpContext.Session.GetString("HomeClient");
            Manager manager = JsonSerializer.Deserialize<Manager>(usertJson);
            // Передача об'єкту менеджера до представлення
            return View(manager);
        }

        // Дія для відображення профілю менеджера (POST-запит)
        [HttpPost]
        [Route("ManagerController/Profile")]
        public IActionResult Profile(string button) {
            switch (button)
            {
                case "create":
                    // Перенаправлення на сторінку створення співробітника
                    return RedirectToAction("CreateEmployee");
                case "view":
                    // Перенаправлення на сторінку звітів
                    return RedirectToAction("Reports");
                case "add":
                    // Перенаправлення на сторінку додавання спеціалізації
                    return RedirectToAction("AddSpec");
            }
            return View();
        }

        // Дія для створення співробітника (GET-запит)
        [HttpGet]
        [Route("ManagerController/CreateEmployee")]
        public IActionResult CreateEmployee() {
            // Створення об'єкту для передачі даних на сторінку
            UserRegist userRegist = new UserRegist();
            string sql = "SELECT specialty FROM specialty";
            userRegist.Specialties = _performer.ListQueryFirstOrDefault(sql);
            return View(userRegist);
        }

        // Дія для створення співробітника (POST-запит)
        [HttpPost]
        [Route("ManagerController/CreateEmployee")]
        public IActionResult CreateEmployee(Employee employee) {
            employee.Specialty++;
            Console.WriteLine(employee.Specialty);
            UserRegist userRegist = Validation.CreateEmployee(employee, _performer);
            string sql = "SELECT specialty FROM specialty";
            userRegist.Specialties = _performer.ListQueryFirstOrDefault(sql);
            return View(userRegist);
        }

        // Дія для відображення сторінки звітів (GET-запит)
        [HttpGet]
        [Route("ManagerController/Reports")]
        public IActionResult Reports() {
            Console.WriteLine("Reportsget");
            return View();
        }

        // Дія для відображення сторінки звітів (POST-запит)
        [HttpPost]
        [Route("ManagerController/Reports")]
        public IActionResult Reports(string button) {
            Console.WriteLine("Reports");
            switch (button)
            {
                case "employee":
                    // Перенаправлення на сторінку звітів про співробітників
                    return RedirectToAction("EmployeeReports");
                case "orders":
                    // Перенаправлення на сторінку звітів про замовлення
                    return RedirectToAction("AllOrders");
                case "rating":
                    // Перенаправлення на сторінку популярності спеціалізацій
                    return RedirectToAction("PopularSpec");
                case "clientorder":
                    // Перенаправлення на сторінку перегляду замовлень клієнтів
                    return RedirectToAction("ClientOrderView");
            }
            return View();
        }

        // Дія для відображення звіту про співробітників (GET-запит)
        [HttpGet]
        [Route("ManagerController/EmployeeReports")]
        public IActionResult EmployeeReports() {
            // Отримання списку всіх співробітників
            List<Employee> employees = Validation.AllEmp(_performer);

            // Створення об'єкту для передачі даних на сторінку
            ReportEmpView viewModel = new ReportEmpView
            {
                Employees = employees
            };

            // Передача об'єкту до представлення
            return View(viewModel);
        }

        // Дія для відображення звіту про співробітників (POST-запит)
        [HttpPost]
        [Route("ManagerController/EmployeeReports")]
        public IActionResult EmployeeReports(int EmployeeId, DateTime StartDateTime, DateTime EndDateTime) {
            // Отримання результатів звіту
            CompliteOrdEmp result = Validation.ReportsEmpOrd(EmployeeId, StartDateTime, EndDateTime, _performer);

            // Отримання списку всіх співробітників
            List<Employee> employees = Validation.AllEmp(_performer);
            Console.WriteLine($"ORDER={result.TotalOrders}+{result.TotalRevenue}+{result.TenPercent}");

            // Створення об'єкту для передачі даних на сторінку
            ReportEmpView viewModel = new ReportEmpView
            {
                Employees = employees,
                ReportResult = result
            };

            // Передача об'єкту до представлення
            return View(viewModel);
        }

        // Дія для відображення звіту про всі замовлення (GET-запит)
        [HttpGet]
        [Route("ManagerController/AllOrders")]
        public IActionResult AllOrders() {
            return View();
        }

        // Дія для відображення звіту про всі замовлення (POST-запит)
        [HttpPost]
        [Route("ManagerController/AllOrders")]
        public IActionResult AllOrders(DateTime StartDateTime, DateTime EndDateTime) {
            // Отримання результатів звіту
            CompliteOrdEmp result = Validation.AllOrders(StartDateTime, EndDateTime, _performer);
            Console.WriteLine($"ORDER={result.TotalRevenue}+{result.TenPercent}");

            // Передача результатів до представлення
            return View(result);
        }

        // Дія для відображення списку популярних спеціалізацій (GET-запит)
        [HttpGet]
        [Route("ManagerController/PopularSpec")]
        public IActionResult PopularSpec() {
            // Отримання списку популярних спеціалізацій
            List<RatingSpec> ratingSpecs = Validation.GetRatingSpec(_performer);

            // Передача списку до представлення
            return View(ratingSpecs);
        }

        // Дія для відображення списку замовлень клієнтів (GET-запит)
        [HttpGet]
        [Route("ManagerController/ClientOrderView")]
        public IActionResult ClientOrderView() {
            // Отримання списку замовлень клієнтів
            List<ClientOrder> list = Validation.GetClientOrder(_performer);

            // Передача списку до представлення
            return View(list);
        }

        // Дія для відображення сторінки додавання спеціалізації (GET-запит)
        [HttpGet]
        [Route("ManagerController/AddSpec")]
        public IActionResult AddSpec() {
            return View();
        }

        // Дія для додавання спеціалізації (POST-запит)
        [HttpPost]
        [Route("ManagerController/AddSpec")]
        public IActionResult AddSpec(string spec) {
            Console.WriteLine(spec);
            // Додавання спеціалізації до бази даних
            Validation.AddSpec(spec, _performer);

            return View();
        }

    }
}

Views/Manager/AddSpec.cshtml
@{
  
}
<style>
    .custom-button {
        position: fixed;
        top: 20px;
        right: 20px;
        padding: 10px 20px;
        background-color: #337ab7;
        color: #fff;
        border-radius: 50px;
        text-decoration: none;
        font-size: 16px;
        font-weight: bold;
        border: none;
        outline: none;
        z-index: 9999;
        transition: background-color 0.3s ease;
    }

        .custom-button:hover {
            background-color: #23527c;
        }
</style>
<h1>@ViewData["Title"]</h1>
<a href="@Url.Action("Profile", "Manager")" class="custom-button">Повернутися</a>
<form method="post" asp-action="AddSpec" asp-controller="ManagerController">
    <div class="form-group">
        <label for="inputField">Додати спеціальність:</label>
        <input type="text" class="form-control" id="inputField" name="spec" required>
    </div>

    <button type="submit" class="btn btn-primary">Додати</button>
</form>

Views/Manager/AllOrders.cshtml
<style>
    .custom-button {
        position: fixed;
        top: 20px;
        right: 20px;
        padding: 10px 20px;
        background-color: #337ab7;
        color: #fff;
        border-radius: 50px;
        text-decoration: none;
        font-size: 16px;
        font-weight: bold;
        border: none;
        outline: none;
        z-index: 9999;
        transition: background-color 0.3s ease;
    }

        .custom-button:hover {
            background-color: #23527c;
        }

    .form-group {
        margin-bottom: 10px;
    }

        .form-group label {
            font-weight: bold;
        }

    .form-control {
        width: 250px; /* Измените значение ширины по вашему выбору */
        padding: 6px 12px;
        font-size: 14px;
        border-radius: 4px;
        border: 1px solid #ccc;
    }

    .btn-primary {
        background-color: #007bff;
        color: #fff;
        border: none;
        padding: 8px 16px;
        border-radius: 4px;
        cursor: pointer;
    }

        .btn-primary:hover {
            background-color: #0056b3;
        }

    .container {
        margin-top: 20px;
    }

    .mt-4 {
        margin-top: 20px;
    }

    .mb-2 {
        margin-bottom: 10px;
    }

    .lead {
        font-size: 18px;
        font-weight: bold;
    }
</style>

<a href="@Url.Action("Profile", "Manager")" class="custom-button">Повернутися</a>

<div class="form-wrapper">
    <form method="post" asp-action="AllOrders" asp-controller="ManagerController">
        <div class="form-group">
            <label for="StartDateTime">Початок пошуку:</label>
            <input type="datetime-local" id="StartDateTime" name="StartDateTime" class="form-control" required />
        </div>
        <div class="form-group">
            <label for="EndDateTime">Кінець пошуку:</label>
            <input type="datetime-local" id="EndDateTime" name="EndDateTime" class="form-control" required />
        </div>
        <button type="submit" name="button" value="employee" class="btn btn-primary">Перевірити</button>
    </form>

    @if (Model != null)
    {
        <div class="container">
            <h2 class="mt-4">Результати:</h2>
            <div class="row">
                <div class="col-md-6">
                    <p class="mb-2">Кількість заказів за період часу:</p>
                    <p class="lead">@Model.TotalOrders</p>
                </div>
                <div class="col-md-6">
                    <p class="mb-2">Дохід:</p>
                    <p class="lead">@Model.TotalRevenue</p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <p class="mb-2">10% від доходу робітнику:</p>
                    <p class="lead">@Model.TenPercent</p>
                </div>
            </div>
        </div>
    }
</div>

Views/Manager/ClientOrderView.cshtml
@using coursework.Models.DataModels
@model List<ClientOrder>
<style>
    .custom-button {
        position: fixed;
        top: 20px;
        right: 20px;
        padding: 10px 20px;
        background-color: #337ab7;
        color: #fff;
        border-radius: 50px;
        text-decoration: none;
        font-size: 16px;
        font-weight: bold;
        border: none;
        outline: none;
        z-index: 9999;
        transition: background-color 0.3s ease;
    }

        .custom-button:hover {
            background-color: #23527c;
        }
</style>
<a href="@Url.Action("Profile", "Manager")" class="custom-button">Повернутися</a>
<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>Повне ім'я</th>
            <th>Спеціальність</th>
            <th>Час регістрації заказу</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
                <tr>
            <td>@item.FullName</td>
            <td>@item.Specialty</td>
            <td>@item.OrderTime</td>
                </tr>
        }
    </tbody>
</table>

Views/Manager/CreateEmployee.cshtml
@model coursework.Models.TriggerModel.UserRegist

@{
    ViewData["Title"] = "Create Employee";
}

<head>
    <style>
        .form-wrapper {
            background-color: #f1f1f1;
            padding: 20px;
        }

            .form-wrapper .form-group {
                margin-bottom: 20px;
            }

        .result-error {
            color: red;
        }

        .result-success {
            color: green;
        }
    </style>
</head>
<style>
    .custom-button {
        position: fixed;
        top: 20px;
        right: 20px;
        padding: 10px 20px;
        background-color: #337ab7;
        color: #fff;
        border-radius: 50px;
        text-decoration: none;
        font-size: 16px;
        font-weight: bold;
        border: none;
        outline: none;
        z-index: 9999;
        transition: background-color 0.3s ease;
    }

        .custom-button:hover {
            background-color: #23527c;
        }
</style>
<a href="@Url.Action("Profile", "Manager")" class="custom-button">Повернутися</a>
<p>Заповніть дані</p>
<div>
    <div class="form-wrapper">
        <form method="post" asp-action="CreateEmployee" asp-controller="ManagerController">
            <div class="form-group">
                <label for="login">Логін:</label>
                <input type="text" class="form-control" id="login" name="login" required>
            </div>
            <div class="form-group">
                <label for="password">Пароль:</label>
                <input type="password" class="form-control" id="password" name="password" required>
            </div>
            <div class="form-group">
                <label for="fio">Ім'я та призвище:</label>
                <input type="text" class="form-control" id="name" name="Name" required>
                <input type="text" class="form-control" id="name" name="Surname" required>
            </div>
            <div class="form-group">
                <label for="specialty">Спеціальність:</label>
                <select class="form-control" id="specialty" name="Specialty" required>
                    @for (int i = 0; i < Model.Specialties.Count; i++)
                    {
                        <option value="@i">@Model.Specialties[i]</option>
                    }
                </select>
                <input type="hidden" id="selectedRow" name="SelectedRow" value="">
            </div>
            <div class="form-group">
                <label for="email">Email:</label>
                <input type="email" class="form-control" id="email" name="email" required>
            </div>
            <div>
                <button type="submit" class="btn btn-primary">Відправити</button>
            </div>
        </form>
    </div>
    @if (Model != null)
    {
        <div class="result @(Model.IsRegistered ? "result-success" : "result-error")">
            @Model.Result
        </div>
    }
</div>

<script>
    var selectElement = document.getElementById("specialty");
    var hiddenInput = document.getElementById("selectedRow");

    selectElement.addEventListener("change", function () {
        hiddenInput.value = selectElement.selectedIndex;
    });
</script>

Views/Manager/EmployeeReports.cshtml
@using coursework.Models.DataModels
@model ReportEmpView

@{

}

<h1>@ViewData["Title"]</h1>



<style>
    .custom-button {
        position: fixed;
        top: 20px;
        right: 20px;
        padding: 10px 20px;
        background-color: #337ab7;
        color: #fff;
        border-radius: 50px;
        text-decoration: none;
        font-size: 16px;
        font-weight: bold;
        border: none;
        outline: none;
        z-index: 9999;
        transition: background-color 0.3s ease;
    }

        .custom-button:hover {
            background-color: #23527c;
        }

    .form-group {
        margin-bottom: 10px;
    }

        .form-group label {
            font-weight: bold;
        }

    .form-control {
        width: 250px; /* Измените значение ширины по вашему выбору */
        padding: 6px 12px;
        font-size: 14px;
        border-radius: 4px;
        border: 1px solid #ccc;
    }

    .btn-primary {
        background-color: #007bff;
        color: #fff;
        border: none;
        padding: 8px 16px;
        border-radius: 4px;
        cursor: pointer;
    }

        .btn-primary:hover {
            background-color: #0056b3;
        }

    .container {
        margin-top: 20px;
    }

    .mt-4 {
        margin-top: 20px;
    }

    .mb-2 {
        margin-bottom: 10px;
    }

    .lead {
        font-size: 18px;
        font-weight: bold;
    }
</style>

<a href="@Url.Action("Profile", "Manager")" class="custom-button">Повернутися</a>

<div class="form-wrapper">
    <form asp-action="EmployeeReports" asp-controller="ManagerController" method="post">
        <div class="form-group">
            <label for="EmployeeId">Employee:</label>
            <select id="EmployeeId" name="EmployeeId" class="form-control" required>
                @foreach (var employee in Model.Employees)
                {
                    <option value="@employee.Id">@employee.Id - @employee.Name @employee.Surname</option>
                }
            </select>
        </div>
        <div class="form-group">
            <label for="StartDateTime">Start Date and Time:</label>
            <input type="datetime-local" id="StartDateTime" name="StartDateTime" class="form-control"  required />
        </div>
        <div class="form-group">
            <label for="EndDateTime">End Date and Time:</label>
            <input type="datetime-local" id="EndDateTime" name="EndDateTime" class="form-control"  required />
        </div>
        <button type="submit" name="button" value="employee" class="btn btn-primary">Перевірити</button>
    </form>
</div>

@if (Model.ReportResult != null)
{
    <div class="container">
        <h2 class="mt-4">Результаты:</h2>
        <div class="row">
            <div class="col-md-6">
                <p class="mb-2">Кількість заказів за період часу:</p>
                <p class="lead">@Model.ReportResult.TotalOrders</p>
            </div>
            <div class="col-md-6">
                <p class="mb-2">Дохід:</p>
                <p class="lead">@Model.ReportResult.TotalRevenue</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <p class="mb-2">10% від доходу робітнику:</p>
                <p class="lead">@Model.ReportResult.TenPercent</p>
            </div>
        </div>
    </div>
}

Views/Manager/PopularSpec.cshtml
@using coursework.Models.DataModels
@model List<RatingSpec>
<style>
    .custom-button {
        position: fixed;
        top: 20px;
        right: 20px;
        padding: 10px 20px;
        background-color: #337ab7;
        color: #fff;
        border-radius: 50px;
        text-decoration: none;
        font-size: 16px;
        font-weight: bold;
        border: none;
        outline: none;
        z-index: 9999;
        transition: background-color 0.3s ease;
    }

        .custom-button:hover {
            background-color: #23527c;
        }
</style>
<a href="@Url.Action("Profile", "Manager")" class="custom-button">Повернутися</a>
<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>ID</th>
            <th>Спеціальність</th>
            <th>Рейтинг</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Specialty</td>
                <td>@item.Rating %</td>
            </tr>
        }
    </tbody>
</table>

Views/Manager/Profile.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Профіль менеджера</title>

    <!-- Подключение стилей Bootstrap -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" />

    <style>
        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }

        .top-panel {
            display: flex;
            justify-content: space-between;
            margin-bottom: 20px;
        }

        .left-buttons {
            display: flex;
            align-items: center;
        }

        .right-buttons {
            display: flex;
            align-items: center;
        }

        .button {
            margin-right: 10px;
        }

        .card {
            border: 1px solid #ccc;
            border-radius: 5px;
            padding: 20px;
        }

        .card-title {
            margin-top: 0;
        }

        .card-content {
            margin-bottom: 20px;
        }

            .card-content p {
                margin: 0;
            }

        .custom-button {
            position: fixed;
            top: 20px;
            right: 20px;
            padding: 10px 20px;
            background-color: #337ab7;
            color: #fff;
            border-radius: 50px;
            text-decoration: none;
            font-size: 16px;
            font-weight: bold;
            border: none;
            outline: none;
            z-index: 9999;
            transition: background-color 0.3s ease;
        }

            .custom-button:hover {
                background-color: #23527c;
            }
    </style>
</head>
<body>
    <a href="@Url.Action("index", "Home")" class="custom-button">Вийти з облікового запису</a>
    <div class="container">
        <h1>Профиль менеджера</h1>
        <form method="post" asp-action="Profile" asp-controller="ManagerController">
            <div>
                <div>
                    <button type="submit" name="button" value="create" class="btn btn-primary">Додати робітника</button>
                    <button type="submit" name="button" value="add" class="btn btn-primary">Додати спеціальність</button>
                    <button type="submit" name="button" value="view" class="btn btn-primary">Зробити звітність</button>
                </div>
            </div>
        </form>

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Інформація про менеджера</h5>
                <div class="card-content">
                    <p><strong>Ім'я':</strong> @Model.Name</p>
                    <p><strong>Призвище':</strong> @Model.Surname</p>
                    <p><strong>Login:</strong>@Model.Login</p>
</body>

Views/Manager/Reports.cshtml
@{
    ViewData["Title"] = "Button Example";
}

<!DOCTYPE html>
<html>
<head>
    <title>Button Example</title>
    <style>
        .custom-button {
            margin: 10px 0;
            display: block;
            background-color: #428bca;
            color: white;
            border: none;
            width: 100%;
            height: 120px;
            font-size: 40px;
        }

            .custom-button:hover {
                background-color: #3276b1;
            }
    </style>
</head>
<body>
    <div class="container">
        <form method="post" asp-action="Reports" asp-controller="ManagerController">
            <button type="submit" name="button" value="employee" class="custom-button">Перевірити роботу робітника</button>
            <button type="submit" name="button" value="orders" class="custom-button">Усі виконані закази</button>
            <button type="submit" name="button" value="rating" class="custom-button">Рейтинг спеціалізацій</button>
            <button type="submit" name="button" value="clientorder" class="custom-button">переглянути замовлення від клієнтів</button>
        </form>
    </div>
</body>
</html>